/**
 * Generates `packages/core/tags.json` — search tags for the catalog.
 *
 * Tags are built from the icon name instead of being written by hand for each
 * of the 382: the icon list keeps growing, and a manual file would drift from
 * the folder on the very first batch. The rules below cover three cases:
 *
 *   1. parts of a compound name   (`arrow-circle-down` → arrow, circle, down)
 *   2. synonyms for the parts     (`trash` → delete, remove, bin)
 *   3. a theme by keyword        (`file-js` → code, development)
 *
 * English only: the catalog is English, and mixed languages in one index hurt
 * Fuse ranking — a latin query starts catching cyrillic entries.
 *
 * Run: `npm run tags:build` (part of `npm run build`).
 */
import { writeFileSync } from 'node:fs'
import { join } from 'node:path'

import { collectIcons, ROOT } from './svg-source.mjs'

/** Synonyms for single words of a name. Key is the word, value is what to add. */
const SYNONYMS = {
  airplane: ['plane', 'flight', 'travel', 'aviation'],
  alarm: ['clock', 'time', 'wake', 'reminder'],
  alien: ['ufo', 'space', 'extraterrestrial'],
  align: ['layout', 'position', 'distribute'],
  ambulance: ['emergency', 'medical', 'hospital'],
  anchor: ['ship', 'nautical', 'marine'],
  angle: ['geometry', 'corner', 'degree'],
  aperture: ['camera', 'photo', 'lens'],
  archive: ['box', 'storage', 'backup'],
  armchair: ['furniture', 'seat', 'chair'],
  arrow: ['direction', 'pointer', 'navigation'],
  arrows: ['direction', 'pointer', 'navigation'],
  asterisk: ['star', 'footnote', 'wildcard'],
  atom: ['science', 'physics', 'molecule'],
  avocado: ['food', 'fruit', 'healthy'],
  axe: ['tool', 'chop', 'weapon'],
  baby: ['child', 'infant', 'kid'],
  backpack: ['bag', 'school', 'travel', 'hiking'],
  backspace: ['delete', 'erase', 'keyboard', 'undo'],
  bag: ['shopping', 'purse', 'store', 'purchase'],
  balloon: ['party', 'celebration', 'birthday', 'float'],
  bandaids: ['plaster', 'medical', 'injury', 'first aid'],
  bank: ['finance', 'money', 'building', 'institution'],
  barbell: ['gym', 'fitness', 'weight', 'workout'],
  barcode: ['scan', 'product', 'retail', 'code'],
  barn: ['farm', 'agriculture', 'rural', 'building'],
  barricade: ['block', 'roadblock', 'construction', 'barrier'],
  baseball: ['sport', 'ball', 'game'],
  basket: ['shopping', 'cart', 'store', 'container'],
  basketball: ['sport', 'ball', 'game', 'hoop'],
  bathtub: ['bath', 'bathroom', 'wash', 'tub'],
  battery: ['power', 'charge', 'energy'],
  beach: ['sea', 'summer', 'vacation', 'sand'],
  beanie: ['hat', 'winter', 'clothing', 'cap'],
  bed: ['sleep', 'bedroom', 'hotel', 'rest'],
  beer: ['drink', 'alcohol', 'bar', 'pub'],
  behance: ['logo', 'brand', 'portfolio', 'design'],
  bell: ['notification', 'alert', 'ring'],
  belt: ['clothing', 'accessory', 'waist'],
  bezier: ['curve', 'vector', 'path', 'design'],
  bicycle: ['bike', 'cycling', 'transport', 'ride'],
  binary: ['code', 'data', 'digital', 'bits'],
  biohazard: ['danger', 'warning', 'toxic', 'hazard'],
  bird: ['animal', 'fly', 'nature', 'wing'],
  blueprint: ['plan', 'design', 'architecture', 'draft'],
  bluetooth: ['wireless', 'connection', 'pairing', 'signal'],
  boat: ['ship', 'sail', 'water', 'transport'],
  bomb: ['explosive', 'danger', 'blast', 'destroy'],
  bone: ['skeleton', 'anatomy', 'dog', 'medical'],
  book: ['read', 'library', 'literature', 'study'],
  bookmark: ['save', 'favorite', 'mark', 'remember'],
  bookmarks: ['save', 'favorites', 'marks', 'collection'],
  books: ['library', 'read', 'study', 'collection'],
  boot: ['shoe', 'footwear', 'clothing'],
  boules: ['petanque', 'game', 'sport', 'ball'],
  bounding: ['box', 'frame', 'select'],
  bowl: ['food', 'dish', 'kitchen', 'meal'],
  bowling: ['sport', 'game', 'strike', 'ball'],
  boxing: ['sport', 'fight', 'glove', 'punch'],
  brackets: ['code', 'syntax', 'programming', 'parentheses'],
  brain: ['mind', 'think', 'intelligence', 'neuro'],
  brandy: ['drink', 'alcohol', 'glass', 'bar'],
  bread: ['food', 'bakery', 'loaf', 'eat'],
  bridge: ['cross', 'connect', 'structure', 'architecture'],
  briefcase: ['work', 'business', 'bag', 'office'],
  broadcast: ['signal', 'stream', 'radio', 'transmit'],
  broom: ['clean', 'sweep', 'housework'],
  browser: ['web', 'internet', 'window', 'site'],
  browsers: ['web', 'internet', 'windows', 'tabs'],
  calendar: ['date', 'schedule', 'event', 'month'],
  caret: ['arrow', 'chevron', 'triangle', 'expand'],
  circle: ['round', 'shape', 'ellipse'],
  circles: ['round', 'shape', 'group'],
  clock: ['time', 'schedule', 'watch', 'hour'],
  columns: ['layout', 'grid', 'table', 'split'],
  compass: ['navigation', 'direction', 'tool'],
  crop: ['cut', 'trim', 'image', 'edit'],
  cube: ['3d', 'box', 'shape', 'volume'],
  cylinder: ['3d', 'shape', 'database', 'volume'],
  diamonds: ['shape', 'gem', 'cards'],
  drop: ['water', 'liquid', 'droplet', 'opacity'],
  eraser: ['delete', 'remove', 'clear', 'edit'],
  exclude: ['boolean', 'shape', 'subtract', 'path'],
  eye: ['view', 'visibility', 'see', 'preview'],
  file: ['document', 'page', 'paper'],
  files: ['documents', 'pages', 'copy'],
  flip: ['mirror', 'reverse', 'transform'],
  folder: ['directory', 'storage', 'files'],
  folders: ['directories', 'storage', 'files'],
  grid: ['layout', 'table', 'gallery'],
  hexagon: ['shape', 'polygon', 'six'],
  hourglass: ['time', 'wait', 'loading', 'timer'],
  intersect: ['boolean', 'shape', 'overlap', 'path'],
  layout: ['grid', 'template', 'arrange', 'design'],
  number: ['digit', 'numeric', 'count'],
  octagon: ['shape', 'polygon', 'eight', 'stop'],
  parallelogram: ['shape', 'geometry', 'skew'],
  pen: ['write', 'draw', 'edit', 'design'],
  pencil: ['write', 'draw', 'edit'],
  pentagon: ['shape', 'polygon', 'five'],
  pentagram: ['star', 'shape', 'occult'],
  perspective: ['3d', 'transform', 'view'],
  placeholder: ['empty', 'blank', 'stub'],
  rectangle: ['shape', 'square', 'box'],
  recycle: ['reuse', 'environment', 'sustainability'],
  resize: ['scale', 'transform', 'size'],
  rows: ['layout', 'table', 'list', 'split'],
  selection: ['select', 'marquee', 'highlight'],
  sidebar: ['panel', 'menu', 'navigation', 'layout'],
  square: ['shape', 'box', 'rectangle'],
  squares: ['shape', 'grid', 'boxes'],
  stack: ['layers', 'pile', 'group'],
  subtract: ['boolean', 'minus', 'shape', 'path'],
  timer: ['time', 'countdown', 'stopwatch'],
  triangle: ['shape', 'polygon', 'three'],
  unite: ['boolean', 'merge', 'combine', 'shape'],
  vector: ['path', 'design', 'graphics'],
  vignette: ['photo', 'filter', 'effect'],
  watch: ['time', 'clock', 'wearable'],
  acorn: ['nut', 'oak', 'nature', 'autumn'],
  address: ['contact', 'book', 'phone'],
  airplay: ['cast', 'stream', 'screen', 'apple'],
  amazon: ['brand', 'logo', 'shop'],
  android: ['brand', 'logo', 'mobile', 'google'],
  angular: ['brand', 'logo', 'framework', 'code'],
  apple: ['brand', 'logo'],
  approximate: ['math', 'equals', 'roughly'],
  article: ['news', 'text', 'read', 'blog'],
  asclepius: ['medical', 'health', 'snake', 'doctor'],
  at: ['email', 'mention', 'address'],
  carriage: ['stroller', 'pram', 'child'],
  charging: ['power', 'energy', 'plug'],
  check: ['done', 'tick', 'confirm', 'success'],
  clockwise: ['rotate', 'turn', 'redo'],
  closed: ['shut', 'hidden'],
  code: ['development', 'programming', 'source'],
  countdown: ['timer', 'time', 'wait'],
  dashed: ['dotted', 'outline', 'border'],
  dot: ['point', 'bullet', 'circle'],
  dots: ['points', 'menu', 'more'],
  down: ['bottom', 'south', 'below'],
  empty: ['blank', 'none', 'zero'],
  full: ['complete', 'max', 'filled'],
  half: ['partial', 'fifty'],
  heart: ['love', 'favorite', 'like'],
  high: ['max', 'top', 'level'],
  horizontal: ['x', 'width', 'row'],
  in: ['inside', 'enter', 'collapse'],
  inverse: ['invert', 'opposite', 'reverse'],
  left: ['west', 'back', 'previous'],
  lock: ['secure', 'private', 'password'],
  low: ['min', 'bottom', 'level'],
  magnifying: ['search', 'zoom', 'find', 'glass'],
  medium: ['mid', 'level', 'brand'],
  merge: ['combine', 'join', 'union'],
  minus: ['remove', 'subtract', 'delete', 'less'],
  notch: ['loading', 'spinner', 'progress'],
  open: ['unlock', 'expand', 'unfold'],
  out: ['outside', 'exit', 'expand'],
  plus: ['add', 'new', 'create', 'more'],
  right: ['east', 'forward', 'next'],
  ringing: ['alert', 'notification', 'sound'],
  simple: ['minimal', 'basic', 'plain'],
  slash: ['off', 'disabled', 'mute', 'none'],
  split: ['divide', 'separate', 'half'],
  star: ['favorite', 'bookmark', 'rating'],
  takeoff: ['departure', 'launch', 'start'],
  landing: ['arrival', 'land', 'descend'],
  three: ['3'],
  tilt: ['angle', 'rotate', 'skew'],
  top: ['up', 'above', 'north'],
  transparent: ['opacity', 'alpha', 'clear'],
  two: ['2'],
  up: ['top', 'north', 'above'],
  user: ['person', 'account', 'profile', 'avatar'],
  vertical: ['y', 'height', 'column'],
  warning: ['alert', 'caution', 'error'],
  x: ['close', 'cancel', 'remove', 'cross'],
  z: ['sleep', 'snooze', 'mute'],

  // Added once 181 single-word icon names turned up with zero tags: they had
  // no hyphen for the multi-word fallback below to catch, and none of them
  // happened to be in the blocks above.
  bug: ['insect', 'error', 'glitch', 'issue'],
  building: ['office', 'skyscraper', 'architecture', 'tower'],
  buildings: ['office', 'skyscrapers', 'city', 'architecture'],
  bulldozer: ['construction', 'excavator', 'heavy equipment', 'tractor'],
  bus: ['transit', 'vehicle', 'transport', 'coach'],
  butterfly: ['insect', 'nature', 'moth', 'wings'],
  cactus: ['plant', 'desert', 'succulent', 'nature'],
  cake: ['birthday', 'dessert', 'celebration', 'party'],
  camera: ['photo', 'photography', 'picture', 'snapshot'],
  campfire: ['bonfire', 'outdoors', 'camping', 'flame'],
  car: ['vehicle', 'automobile', 'drive', 'transport'],
  cardholder: ['wallet', 'credit card', 'billfold'],
  cards: ['playing cards', 'poker', 'deck', 'game'],
  carrot: ['vegetable', 'food', 'vegetable garden'],
  cat: ['kitten', 'pet', 'animal', 'feline'],
  certificate: ['diploma', 'award', 'credential', 'document'],
  chair: ['seat', 'furniture', 'sit'],
  chalkboard: ['blackboard', 'teach', 'classroom', 'lesson'],
  chat: ['message', 'conversation', 'bubble', 'talk'],
  chats: ['messages', 'conversation', 'bubbles', 'talk'],
  checkerboard: ['checkers', 'board game', 'grid', 'pattern'],
  checks: ['checkboxes', 'list', 'verified', 'done'],
  cheers: ['toast', 'drinks', 'celebration', 'glasses'],
  cheese: ['food', 'dairy', 'wedge'],
  cherries: ['fruit', 'food', 'cherry'],
  church: ['cathedral', 'religion', 'chapel', 'worship'],
  cigarette: ['smoking', 'tobacco', 'smoke'],
  circuitry: ['circuit board', 'electronics', 'chip', 'technology'],
  city: ['skyline', 'urban', 'buildings', 'metropolis'],
  clipboard: ['checklist', 'notes', 'board', 'task'],
  cloud: ['weather', 'sky', 'storage', 'overcast'],
  clover: ['luck', 'shamrock', 'four leaf', 'plant'],
  club: ['card suit', 'playing card', 'spade'],
  coffee: ['drink', 'cup', 'espresso', 'cafe'],
  coin: ['currency', 'money', 'cash', 'finance'],
  coins: ['currency', 'money', 'cash', 'finance'],
  command: ['cmd key', 'keyboard', 'shortcut', 'mac'],
  confetti: ['celebration', 'party', 'festive'],
  cookie: ['biscuit', 'dessert', 'snack', 'food'],
  copy: ['duplicate', 'clipboard', 'clone'],
  copyleft: ['license', 'open source', 'copyright'],
  couch: ['sofa', 'furniture', 'living room'],
  cow: ['cattle', 'animal', 'farm', 'livestock'],
  cpu: ['processor', 'chip', 'hardware', 'computer'],
  crane: ['construction', 'lift', 'hoist', 'machinery'],
  cricket: ['sport', 'bat and ball', 'insect'],
  cross: ['religion', 'medical', 'plus', 'add'],
  crosshair: ['target', 'aim', 'reticle', 'focus'],
  crown: ['king', 'royal', 'queen', 'premium'],
  cursor: ['pointer', 'arrow', 'click', 'mouse'],
  database: ['storage', 'server', 'data', 'sql'],
  desk: ['workstation', 'table', 'office', 'furniture'],
  desktop: ['computer', 'monitor', 'workstation', 'pc'],
  detective: ['investigator', 'spy', 'mystery', 'sleuth'],
  devices: ['gadgets', 'electronics', 'hardware', 'multi device'],
  diamond: ['gem', 'jewel', 'precious stone', 'card suit'],
  disc: ['cd', 'dvd', 'vinyl', 'record'],
  divide: ['division', 'math', 'operator', 'split'],
  dna: ['genetics', 'helix', 'biology', 'gene'],
  dog: ['puppy', 'pet', 'animal', 'canine'],
  door: ['entrance', 'exit', 'doorway'],
  download: ['save', 'import', 'transfer'],
  dress: ['clothing', 'gown', 'fashion', 'outfit'],
  dresser: ['furniture', 'drawers', 'wardrobe'],
  drone: ['quadcopter', 'uav', 'aerial', 'flying'],
  ear: ['hearing', 'listen', 'audio', 'body'],
  egg: ['food', 'breakfast', 'chicken'],
  eject: ['remove', 'disc', 'unmount'],
  elevator: ['lift', 'building', 'floors'],
  engine: ['motor', 'machine', 'mechanical'],
  envelope: ['mail', 'email', 'message', 'letter'],
  exam: ['test', 'quiz', 'assessment', 'grades'],
  export: ['save as', 'output', 'share'],
  eyedropper: ['color picker', 'pipette', 'sample'],
  eyeglasses: ['glasses', 'spectacles', 'vision', 'reading'],
  eyes: ['vision', 'see', 'look', 'watch'],
  factory: ['manufacturing', 'plant', 'industry', 'warehouse'],
  faders: ['sliders', 'mixer', 'equalizer', 'settings'],
  fan: ['cooling', 'ventilation', 'air', 'breeze'],
  feather: ['quill', 'plume', 'writing', 'bird'],
  fingerprint: ['biometric', 'identity', 'print', 'security'],
  fire: ['flame', 'burn', 'hot'],
  fish: ['seafood', 'aquarium', 'animal', 'swim'],
  flag: ['banner', 'country', 'marker', 'nation'],
  flame: ['fire', 'burn', 'hot', 'streak'],
  flashlight: ['torch', 'light', 'beam'],
  flask: ['chemistry', 'lab', 'science', 'experiment'],
  flower: ['blossom', 'plant', 'bloom', 'nature'],
  football: ['soccer', 'sport', 'ball', 'game'],
  footprints: ['steps', 'walk', 'tracks', 'trail'],
  function: ['formula', 'math', 'code', 'method'],
  funnel: ['filter', 'sort', 'narrow'],
  garage: ['parking', 'car', 'workshop'],
  gauge: ['meter', 'speedometer', 'dial', 'measurement'],
  gavel: ['law', 'judge', 'court', 'hammer'],
  gear: ['settings', 'cog', 'configuration', 'mechanism'],
  ghost: ['spirit', 'halloween', 'spooky', 'phantom'],
  gif: ['animation', 'image', 'media'],
  gift: ['present', 'box', 'birthday', 'surprise'],
  globe: ['world', 'earth', 'planet', 'international'],
  goggles: ['eyewear', 'protection', 'swim', 'ski'],
  golf: ['sport', 'club', 'ball', 'putt'],
  gps: ['location', 'navigation', 'map', 'position'],
  gradient: ['color', 'blend', 'fade'],
  grains: ['wheat', 'cereal', 'food', 'farming'],
  graph: ['chart', 'analytics', 'data', 'statistics'],
  guitar: ['music', 'instrument', 'strings', 'band'],
  handbag: ['purse', 'bag', 'fashion', 'accessory'],
  hash: ['hashtag', 'number sign', 'pound'],
  heartbeat: ['pulse', 'health', 'heart rate', 'cardiogram'],
  house: ['home', 'building', 'residence'],
  image: ['picture', 'photo', 'graphic'],
  images: ['pictures', 'photos', 'gallery'],
  info: ['information', 'help', 'details', 'about'],
  intersection: ['set theory', 'venn diagram', 'overlap', 'math'],
  keyboard: ['type', 'keys', 'input'],
  lamp: ['light', 'lighting', 'desk lamp'],
  lectern: ['podium', 'speech', 'presentation', 'stand'],
  lightbulb: ['idea', 'light', 'bright', 'innovation'],
  lightning: ['bolt', 'thunder', 'electricity', 'flash'],
  link: ['url', 'chain', 'hyperlink', 'connect'],
  list: ['items', 'bullet points', 'menu', 'checklist'],
  magnet: ['attract', 'magnetic', 'physics'],
  megaphone: ['announcement', 'loudspeaker', 'broadcast'],
  microphone: ['mic', 'audio', 'record', 'voice'],
  monitor: ['screen', 'display', 'computer'],
  moon: ['night', 'lunar', 'sky', 'dark mode'],
  mouse: ['cursor', 'pointer', 'click', 'peripheral'],
  network: ['connections', 'nodes', 'internet', 'web'],
  notebook: ['notepad', 'journal', 'book', 'notes'],
  notification: ['alert', 'bell', 'reminder'],
  package: ['box', 'shipping', 'delivery', 'parcel'],
  paperclip: ['attachment', 'clip', 'office supply'],
  pause: ['stop', 'hold', 'media control'],
  peace: ['pacifism', 'harmony', 'anti war', 'nuclear disarmament'],
  phone: ['mobile', 'telephone', 'smartphone', 'call'],
  play: ['start', 'media control', 'video'],
  playlist: ['queue', 'music', 'tracks', 'songs'],
  plug: ['outlet', 'electric', 'power', 'cord'],
  plugs: ['outlet', 'electric', 'power', 'connectors'],
  presentation: ['slideshow', 'slides', 'pitch', 'talk'],
  prohibit: ['forbidden', 'banned', 'no entry', 'restrict'],
  pulse: ['heartbeat', 'vital signs', 'wave', 'signal'],
  question: ['help', 'faq', 'ask', 'unknown'],
  radical: ['square root', 'math', 'symbol'],
  rainbow: ['colors', 'weather', 'arc'],
  receipt: ['invoice', 'bill', 'purchase', 'payment'],
  record: ['vinyl', 'album', 'music', 'media'],
  repeat: ['loop', 'replay', 'again'],
  scan: ['scanner', 'qr code', 'document'],
  screencast: ['screen recording', 'capture', 'broadcast'],
  seal: ['stamp', 'badge', 'official', 'certified'],
  shield: ['protection', 'security', 'defense', 'safety'],
  shuffle: ['random', 'mix', 'playlist'],
  sigma: ['sum', 'math', 'symbol', 'statistics'],
  sliders: ['settings', 'faders', 'adjust', 'controls'],
  slideshow: ['presentation', 'slides', 'photos'],
  smiley: ['emoji', 'face', 'happy', 'emoticon'],
  snowflake: ['winter', 'snow', 'cold', 'frost'],
  spinner: ['loading', 'progress', 'wait'],
  steps: ['stairs', 'walk', 'progress', 'footsteps'],
  sticker: ['label', 'decal', 'emoji'],
  stop: ['halt', 'media control', 'cancel'],
  storefront: ['shop', 'store', 'retail', 'business'],
  suitcase: ['luggage', 'travel', 'briefcase', 'baggage'],
  sun: ['sunshine', 'weather', 'daylight', 'bright'],
  swap: ['exchange', 'switch', 'transfer'],
  tag: ['label', 'price tag', 'category'],
  terminal: ['command line', 'console', 'shell', 'code'],
  thermometer: ['temperature', 'weather', 'measure'],
  tilde: ['symbol', 'approximate', 'punctuation'],
  tote: ['bag', 'carry', 'shopping'],
  trademark: ['brand', 'registered', 'symbol', 'legal'],
  trash: ['delete', 'bin', 'garbage', 'remove'],
  union: ['merge', 'combine', 'set operation'],
  upload: ['send', 'export', 'transfer'],
  users: ['people', 'group', 'team', 'accounts'],
  vibrate: ['phone', 'buzz', 'notification', 'silent mode'],
  waveform: ['audio', 'sound wave', 'frequency', 'signal'],
  waves: ['ocean', 'water', 'sea', 'ripple'],
  wind: ['breeze', 'weather', 'air', 'gust'],
  // Added when 127 icons turned out to be tagged with nothing but their own
  // name spelled with spaces: none of the words their names are built from
  // were in the dictionary above, so there was nothing to expand.
  aid: ['help', 'medical', 'assistance', 'rescue'],
  air: ['sky', 'aviation', 'atmosphere', 'flight'],
  app: ['application', 'software', 'program'],
  ascending: ['up', 'increasing', 'a to z'],
  back: ['previous', 'return', 'reverse', 'backward'],
  badge: ['id', 'pass', 'credential', 'label'],
  ball: ['sphere', 'round', 'sport'],
  bar: ['bars', 'column', 'histogram', 'graph'],
  blank: ['empty', 'plain', 'unwritten'],
  branch: ['fork', 'version control', 'repository', 'split'],
  brush: ['paint', 'draw', 'art', 'stroke'],
  btc: ['bitcoin', 'crypto', 'cryptocurrency'],
  button: ['control', 'toggle', 'press', 'input'],
  can: ['canister', 'container', 'tin', 'jerrycan'],
  cap: ['hat', 'headwear', 'mortarboard'],
  card: ['payment', 'bank', 'id', 'wallet'],
  cart: ['shopping', 'trolley', 'basket', 'checkout'],
  cash: ['money', 'payment', 'till', 'finance'],
  cassette: ['tape', 'audio', 'retro', 'mixtape'],
  castle: ['fortress', 'medieval', 'tower', 'chess'],
  cell: ['mobile', 'phone', 'reception', 'network'],
  chart: ['graph', 'analytics', 'statistics', 'data'],
  chef: ['cook', 'kitchen', 'restaurant', 'culinary'],
  cny: ['yuan', 'renminbi', 'china', 'chinese currency'],
  coat: ['jacket', 'clothing', 'outerwear'],
  commit: ['version control', 'revision', 'changeset', 'save'],
  computer: ['pc', 'desktop', 'machine', 'workstation'],
  contactless: ['nfc', 'tap to pay', 'wireless payment'],
  control: ['manage', 'panel', 'operate'],
  controller: ['gamepad', 'joystick', 'console', 'play'],
  cooking: ['kitchen', 'food', 'recipe', 'cuisine'],
  corners: ['crop', 'frame', 'bounds', 'edges'],
  cowboy: ['western', 'ranch', 'rodeo', 'sheriff'],
  credit: ['payment', 'bank', 'finance', 'debit'],
  currency: ['money', 'finance', 'payment', 'exchange'],
  definition: ['resolution', 'quality', 'sd'],
  descending: ['down', 'decreasing', 'z to a'],
  device: ['gadget', 'hardware', 'phone', 'electronics'],
  diff: ['difference', 'compare', 'changes', 'version control'],
  disco: ['party', 'dance', 'nightclub', 'mirror ball'],
  disk: ['diskette', 'save', 'storage', 'drive'],
  dollar: ['usd', 'money', 'united states', 'currency'],
  donut: ['doughnut', 'ring', 'circle chart'],
  drive: ['disk', 'storage', 'hdd', 'ssd'],
  drives: ['disks', 'storage', 'hdd', 'raid'],
  equal: ['equals', 'math', 'same', 'comparison'],
  equals: ['equal', 'math', 'same', 'comparison'],
  eth: ['ethereum', 'crypto', 'cryptocurrency'],
  eur: ['euro', 'europe', 'european currency'],
  exclamation: ['warning', 'alert', 'important', 'attention'],
  face: ['head', 'expression', 'person'],
  fallout: ['nuclear', 'bunker', 'radiation', 'emergency'],
  fast: ['speed', 'quick', 'rapid'],
  female: ['woman', 'girl', 'venus', 'gender'],
  film: ['movie', 'cinema', 'video', 'reel'],
  finn: ['adventure time', 'cartoon', 'character'],
  first: ['initial', 'primary', 'begin'],
  floppy: ['diskette', 'save', 'retro', 'storage'],
  flying: ['fly', 'airborne', 'hover', 'flight'],
  fork: ['branch', 'cutlery', 'utensil', 'repository'],
  forward: ['next', 'ahead', 'advance', 'skip'],
  frame: ['border', 'crop', 'boundary', 'canvas'],
  game: ['play', 'gaming', 'arcade'],
  gas: ['fuel', 'petrol', 'gasoline', 'station'],
  gbp: ['pound sterling', 'united kingdom', 'britain', 'british currency'],
  gender: ['sex', 'identity', 'symbol'],
  git: ['version control', 'repository', 'source control', 'github'],
  graduation: ['school', 'university', 'education', 'diploma'],
  graphics: ['gpu', 'video card', 'rendering', 'hardware'],
  greater: ['bigger', 'more', 'math', 'comparison'],
  hand: ['palm', 'gesture', 'touch', 'finger'],
  hanger: ['clothes', 'wardrobe', 'closet', 'garment'],
  hard: ['hdd', 'disk', 'storage', 'internal'],
  hat: ['cap', 'headwear', 'clothing'],
  human: ['person', 'people', 'figure'],
  identification: ['id', 'identity', 'credential', 'passport'],
  indent: ['tab', 'text formatting', 'paragraph', 'editor'],
  inr: ['rupee', 'india', 'indian currency'],
  intersex: ['gender', 'identity', 'lgbtq'],
  italic: ['slanted', 'emphasis', 'formatting', 'typography'],
  jpy: ['yen', 'japan', 'japanese currency'],
  key: ['keyboard', 'enter', 'keycap'],
  kit: ['set', 'pack', 'supplies', 'toolbox'],
  knife: ['cutlery', 'blade', 'utensil', 'cut'],
  krw: ['won', 'south korea', 'korean currency'],
  kzt: ['tenge', 'kazakhstan', 'kazakh currency'],
  less: ['smaller', 'fewer', 'math', 'comparison'],
  line: ['stroke', 'segment', 'path', 'graph'],
  male: ['man', 'boy', 'mars', 'gender'],
  map: ['location', 'geography', 'navigation', 'atlas'],
  mark: ['symbol', 'punctuation', 'sign'],
  mask: ['face covering', 'ppe', 'medical', 'protection'],
  math: ['mathematics', 'calculation', 'arithmetic', 'formula'],
  member: ['set theory', 'math', 'element of', 'belongs to'],
  mobile: ['phone', 'smartphone', 'cell', 'handset'],
  music: ['song', 'audio', 'sound', 'melody'],
  neuter: ['gender', 'genderless', 'asexual', 'identity'],
  ngn: ['naira', 'nigeria', 'nigerian currency'],
  nonbinary: ['gender', 'enby', 'identity', 'lgbtq'],
  none: ['empty', 'off', 'zero', 'no signal'],
  note: ['music', 'memo', 'sound'],
  notes: ['music', 'memo', 'sound'],
  operations: ['math', 'arithmetic', 'calculate', 'symbols'],
  outdent: ['untab', 'text formatting', 'paragraph', 'editor'],
  paint: ['draw', 'color', 'art', 'brush'],
  paper: ['sheet', 'document', 'origami'],
  payment: ['pay', 'checkout', 'transaction', 'money'],
  pie: ['circle chart', 'proportion', 'percentage'],
  piece: ['part', 'fragment', 'jigsaw'],
  pin: ['location', 'marker', 'place', 'attach'],
  plane: ['airplane', 'send', 'flight', 'origami'],
  pointing: ['point', 'gesture', 'cursor', 'finger'],
  polar: ['radar chart', 'circular', 'coordinates'],
  pot: ['pan', 'saucepan', 'kitchen', 'cookware'],
  proper: ['strict', 'set theory', 'math'],
  pull: ['fetch', 'merge request', 'version control', 'drag'],
  pump: ['fuel', 'gas station', 'refuel', 'petrol'],
  push: ['press', 'pin', 'send'],
  puzzle: ['jigsaw', 'plugin', 'extension', 'piece'],
  radio: ['option', 'select', 'choice', 'input'],
  reality: ['vr', 'virtual', 'headset', 'immersive'],
  reel: ['film', 'movie', 'cinema', 'spool'],
  register: ['till', 'cashier', 'checkout', 'pos'],
  request: ['ask', 'version control'],
  return: ['enter', 'keyboard', 'newline', 'submit'],
  rewind: ['back', 'replay', 'reverse', 'previous'],
  rotate: ['turn', 'spin', 'orientation', 'flip'],
  rub: ['ruble', 'russia', 'russian currency'],
  saucer: ['ufo', 'alien', 'spaceship', 'extraterrestrial'],
  sawtooth: ['waveform', 'signal', 'audio', 'synth'],
  scatter: ['plot', 'points', 'graph', 'correlation'],
  segment: ['line', 'part', 'section', 'geometry'],
  segments: ['lines', 'parts', 'sections', 'geometry'],
  shelter: ['bunker', 'refuge', 'safety', 'emergency'],
  shopping: ['store', 'buy', 'retail', 'ecommerce'],
  signal: ['reception', 'network', 'bars', 'strength'],
  sine: ['waveform', 'signal', 'audio', 'oscillation'],
  skip: ['next', 'jump', 'track'],
  slate: ['clapperboard', 'film', 'movie', 'director'],
  slice: ['portion', 'segment', 'wedge', 'part'],
  sort: ['order', 'arrange', 'filter', 'rank'],
  speaker: ['audio', 'sound', 'volume', 'loudspeaker'],
  standard: ['sd', 'normal', 'default', 'quality'],
  strikethrough: ['crossed out', 'formatting', 'editor', 'typography'],
  strip: ['film', 'reel', 'sequence', 'frames'],
  structure: ['hierarchy', 'tree', 'organization', 'diagram'],
  subscript: ['below', 'formatting', 'editor', 'typography'],
  subset: ['set theory', 'math', 'venn', 'contained in'],
  superscript: ['above', 'formatting', 'editor', 'typography'],
  superset: ['set theory', 'math', 'venn', 'contains'],
  tablet: ['ipad', 'device', 'touchscreen', 'mobile'],
  tap: ['touch', 'press', 'gesture', 'click'],
  tape: ['cassette', 'audio', 'recording', 'reel'],
  text: ['editor', 'formatting', 'typography', 'font'],
  tower: ['mast', 'antenna', 'case', 'building'],
  traffic: ['control', 'routing', 'flow'],
  transgender: ['gender', 'trans', 'identity', 'lgbtq'],
  tree: ['hierarchy', 'branch', 'nature', 'directory'],
  trifold: ['folded', 'brochure', 'paper map'],
  turret: ['tower', 'castle', 'fortress', 'battlement'],
  underline: ['underlined', 'formatting', 'editor', 'typography'],
  view: ['display', 'show', 'panel', 'browse'],
  virtual: ['vr', 'simulated', 'digital', 'immersive'],
  wave: ['waveform', 'signal', 'oscillation', 'sound'],
  wifi: ['wireless', 'network', 'internet', 'connection'],
  window: ['pane', 'app', 'ui', 'browser'],
}

/** Theme by keyword: one hit gives the icon the whole tag set. */
const THEMES = [
  { when: ['file', 'folder', 'files', 'folders'], tags: ['document', 'storage'] },
  { when: ['arrow', 'arrows', 'caret'], tags: ['direction', 'navigation'] },
  { when: ['circle', 'square', 'triangle', 'hexagon', 'octagon', 'pentagon', 'rectangle', 'parallelogram'], tags: ['shape', 'geometry'] },
  { when: ['align', 'columns', 'rows', 'grid', 'layout', 'sidebar'], tags: ['layout', 'design'] },
  { when: ['battery'], tags: ['device', 'status'] },
  { when: ['calendar', 'clock', 'timer', 'hourglass', 'alarm', 'watch'], tags: ['time'] },
  { when: ['number'], tags: ['number', 'digit'] },
  { when: ['airplane'], tags: ['travel', 'transport'] },
  { when: ['logo'], tags: ['brand', 'logo'] },
  { when: ['selection', 'crop', 'eraser', 'pen', 'pencil', 'bezier'], tags: ['editor', 'tool'] },
  { when: ['unite', 'subtract', 'intersect', 'exclude'], tags: ['boolean', 'path'] },
]

/**
 * Extensions in names like `file-js`: on their own they tell the search
 * nothing, so they expand into the language and the general development theme.
 */
const EXTENSIONS = {
  js: ['javascript', 'code', 'development'],
  jsx: ['javascript', 'react', 'code', 'development'],
  ts: ['typescript', 'code', 'development'],
  tsx: ['typescript', 'react', 'code', 'development'],
  vue: ['javascript', 'code', 'development', 'framework'],
  py: ['python', 'code', 'development'],
  rs: ['rust', 'code', 'development'],
  cpp: ['c++', 'code', 'development'],
  css: ['stylesheet', 'code', 'web'],
  html: ['markup', 'code', 'web'],
  sql: ['database', 'query', 'code'],
  md: ['markdown', 'text', 'readme'],
  ini: ['config', 'settings', 'text'],
  csv: ['spreadsheet', 'data', 'table'],
  xls: ['spreadsheet', 'excel', 'data'],
  ppt: ['presentation', 'slides'],
  doc: ['word', 'text', 'document'],
  pdf: ['document', 'acrobat'],
  txt: ['text', 'plain'],
  svg: ['vector', 'image', 'graphics'],
  png: ['image', 'bitmap', 'picture'],
  jpg: ['image', 'photo', 'picture'],
  zip: ['archive', 'compressed'],
}

/** Digits spelled out — so that `number-3` finds `number-three`. */
const DIGITS = {
  zero: '0', one: '1', two: '2', three: '3', four: '4',
  five: '5', six: '6', seven: '7', eight: '8', nine: '9',
}

const collator = new Intl.Collator('en')

function tagsFor(name) {
  const parts = name.split('-').filter(Boolean)
  const tags = new Set()

  for (const part of parts) {
    // the word itself is not added as a tag: it is already in `name`, which Fuse
    // searches with a higher weight — a duplicate would only blur the ranking
    for (const syn of SYNONYMS[part] ?? []) tags.add(syn)
    if (DIGITS[part]) tags.add(DIGITS[part])
    // expand the extension only for file icons: `file-c`, but not `arrow-in`
    if (parts[0] === 'file' && EXTENSIONS[part]) {
      for (const t of EXTENSIONS[part]) tags.add(t)
    }
  }

  for (const { when, tags: themed } of THEMES) {
    if (when.some((w) => parts.includes(w))) for (const t of themed) tags.add(t)
  }

  /*
   * Headings: `text-h-one` is searched as "h1", not "text h one" — that is how
   * they are called in markup. A separate rule, because it glues two parts of
   * the name into one word, which none of the general passes above does:
   * DIGITS yields "1", but "h" and "1" still stay apart.
   */
  if (parts[0] === 'text' && parts[1] === 'h') {
    tags.add('heading').add('header').add('title')
    const digit = DIGITS[parts[2]]
    if (digit) {
      tags.add(`h${digit}`)
      tags.add(`h ${digit}`)
      tags.add(`heading ${digit}`)
    }
  }

  // the whole multi-word name: `address-book` is found by `address book`
  if (parts.length > 1) tags.add(parts.join(' '))

  return [...tags].filter((t) => /^[a-z0-9 ]+$/.test(t)).sort(collator.compare)
}

const icons = collectIcons()
const out = {}
for (const { name } of icons) {
  const tags = tagsFor(name)
  if (tags.length) out[name] = tags
}

writeFileSync(join(ROOT, 'packages/core/tags.json'), JSON.stringify(out, null, 2) + '\n')

const total = Object.values(out).reduce((n, t) => n + t.length, 0)
const without = icons.length - Object.keys(out).length
console.log(
  `Tags: ${total} across ${Object.keys(out).length} icons` +
    (without ? ` (without tags: ${without})` : ''),
)
