import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

/**
 * Library build: an ESM bundle plus external React.
 * Components in src/ are generated by a script and never edited by hand.
 */
export default defineConfig({
  plugins: [react()],
  build: {
    lib: {
      entry: 'src/index.ts',
      formats: ['es'],
      fileName: () => 'index.js',
    },
    rollupOptions: {
      external: ['react', 'react/jsx-runtime'],
    },
    // there are many icons, but each is a couple of kilobytes; the warning is just noise
    chunkSizeWarningLimit: 2000,
  },
})
